### PR TITLE
Add project structure

### PR DESCRIPTION
**Pull request by scottrohrig**
Initial project structure setup

### CODE REVIEW

**Comment by RogueStorm7** [comment]
Looks good to me

**Review by RogueStorm7 — APPROVED** [review]

**Review by alex-d-marten — APPROVED** [review]
LGTM!

**Comment by scottrohrig** [comment]
This request to pull to commits into main from develop is a bit premature so I closed it for now. We can make a new PR when the time comes for v1.0

**Comment by RogueStorm7** [comment]
Ok

**Pull request closed without merging**
